### ISSUE TITLE
Get the key value pair of record fields

### ISSUE THREAD

**Issue by just4drama** [googleapis/java-bigquery#2613] opened 2023-03-29 02:27 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-bigquery/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version: 
4.  version(s):26.11.0

#### Steps to reproduce

Get the key and values of a record/struct from a Bigquery Java result. 

```
		BigQuery bigquery = BigQueryOptions.newBuilder()
		    .setCredentials(credentials)
		    .build()
		    .getService();


		QueryJobConfiguration queryConfig =
		    QueryJobConfiguration.newBuilder(
		        "SELECT * FROM `table` LIMIT 2")
		    	.setUseLegacySql(false)
		        .build();
        JobId jobId = JobId.of(UUID.randomUUID().toString());
        Job queryJob = bigquery.create(JobInfo.newBuilder(queryConfig).setJobId(jobId).build());
    
        queryJob = queryJob.waitFor();
    
        if (queryJob == null) {
          throw new RuntimeException("Job no longer exists");
        } 
        else if (queryJob.getStatus().getError() != null) {
          throw new RuntimeException(queryJob.getStatus().getError().toString());
        }
        TableResult result = queryJob.getQueryResults();
		for (FieldValueList row : result.iterateAll()) {
			  FieldValue tFieldValue = row.get("fieldwithRecords");
			  FieldValueList tRow = tFieldValue.getRecordValue();
}
```
I can't find any functionality within the Bigquery API that allows you to find the key and value pairs. I've looked at the schema:
`		Schema schema = result.getSchema(); `, and it does show that the value is indeed returning as a record with repeated fields.

**Comment by Neenu1995** [comment] 2023-04-19 18:51
Hi @just4drama ,
It is unclear what issue you are trying to solve. Can you elaborate on what the issue is?

**Comment by Neenu1995** [comment] 2023-05-30 19:48
Closing this due to lack of actionable information.
Feel free to reopen if necessary.

**Closed by Neenu1995** 2023-05-30 19:48 UTC
Labels: needs more info, type: question, api: bigquery
