### ISSUE TITLE
toBuilder() method(s) used for object duplication actually prevent some fields from being modified.

### ISSUE THREAD

**Issue by wheredevel** [googleapis/java-bigquery#1842] opened 2022-02-09 15:13 UTC
https://github.com/googleapis/java-bigquery/blob/727a07a4c6e62d9a2317bd47af81c877eed419e3/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java#L136-L137

In the lines above `QueryJobConfiguration.Builder` constructor copies references to immutable parameter collections (positional/named).  
Therefore an attempt to later call, for example, `addPostionalParameter()` method on that builder instance will result in an exception.  

I don't think this is done by design: the query is allowed to be modified, potentially, making the previously copied parameters incorrect - therefore the parameters should've also been a subject to modification.

**Comment by stephaniewang526** [comment] 2022-02-09 19:07
Could you provide code snippet on what you are trying to do? If you want to re-run a query with different query params, you would need to re-build the `QueryJobConfiguration`.

**Comment by wheredevel** [comment] 2022-02-10 06:51
> If you want to re-run a query with different query params, you would need to re-build the QueryJobConfiguration.

That's exactly what I'm trying to do.  
The only 2 things that should change between the original and the new QueryJobConfiguration are: query and params.  

Consider the following example:
```
Original
---
SELECT * FROM customer WHERE first_name = ? -- original query
first_name => 'Mary'

New
---
SELECT * FROM customer WHERE first_name = ? AND second_name = ? -- new query
first_name => 'Mary'
second_name => 'Smith'
```

I must keep all the original QueryJobConfiguration settings. For example, setMaxResults.  
I assumed the way to do it is through `toBuilder()` method:
```
QueryJobConfiguration originalQueryJobConfiguration = QueryJobConfiguration.newBuilder("SELECT * FROM customer WHERE first_name = ?")
  .addPositionalParameter(QueryParameterValue.string("Mary"))
  .setMaxResults(10)
  .build();
...
QueryJobConfiguration newQueryJobConfiguration = originalQueryJobConfiguration.toBuilder()
  .setQuery(originalQueryJobConfiguration.getQuery() + " AND second_name = ?")
  .addPositionalParameter(QueryParameterValue.string("Smith"))
  .build();
```
The line `.addPositionalParameter(QueryParameterValue.string("Smith"))` will fail, due to the reasons described in the issue.

**Comment by stephaniewang526** [comment] 2022-02-11 15:51
I see. For the second query, the following would work:
```
QueryJobConfiguration newQueryJobConfiguration = QueryJobConfiguration.newBuilder("SELECT * FROM customer WHERE first_name = ? AND second_name = ? ")
   ...
  .addPositionalParameter(QueryParameterValue.string("Mary"))
  .addPositionalParameter(QueryParameterValue.string("Smith"))
  .setMaxResults(10)
  .build();
```
But I understand that you would like to modify the previous `QueryJobConfiguration` instead of building a fresh new one. I will check to see if this is done by design or should be fixed.

**Comment by wheredevel** [comment] 2022-02-11 19:45
Yes, you got it right.  
Appreciate a quick response!

**Comment by stephaniewang526** [comment] 2022-02-25 16:39
Hi, we can add a new method e.g. `updatePositionalParameter` to allow passing updated positional/names params but we don't plan on changing the existing behavior around `toBuilder()` throughout the SDK... would that be something that could help you?

**Comment by wheredevel** [comment] 2022-02-25 18:57
> Hi, we can add a new method e.g. `updatePositionalParameter` to allow passing updated positional/names params but we don't plan on changing the existing behavior around `toBuilder()` throughout the SDK... would that be something that could help you?
My special case is such, that I can "override" the `toBuilder()` implementation to, actually, redirect to `newBuilder()` and then invoking field setters one-by-one (duplication). I simply replace the collections with mutable variants. Then parameter modification is not a problem.

**Comment by stephaniewang526** [comment] 2022-03-01 01:26
Okay, so sounds like you don't need the `updatePositionalParameter` method?

**Comment by wheredevel** [comment] 2022-03-01 08:36
> Okay, so sounds like you don't need the `updatePositionalParameter` method?

Me, personally - no.

**Comment by stephaniewang526** [comment] 2022-03-03 16:33
Okay, closing per comment above.

**Closed by stephaniewang526** 2022-03-03 16:33 UTC
Labels: type: question, api: bigquery
