### ISSUE TITLE
BigQuery.create() cannot handle "Already Exists" for non-US jobs.

### ISSUE THREAD

**Issue by baeminbo** [googleapis/java-bigquery#1877] opened 2022-03-02 09:04 UTC
The following code suggested in BigQuery public doc [1] cannot handle some errors properly, and fails with `Already Exists` errors.

```java
  public static void loadCsvFromGcs(...) {
    try {
      BigQuery bigquery = BigQueryOptions.getDefaultInstance().getService();
      ...
      Job job = bigquery.create(JobInfo.of(loadConfig));
      job = job.waitFor();
      if (job.isDone()) {
        System.out.println("CSV from GCS successfully added during load append job");
      } else {
        System.out.println(
            "BigQuery was unable to load into the table due to an error:"
                + job.getStatus().getError());
      }
    } catch (BigQueryException | InterruptedException e) {
      System.out.println("Column not added during load append \n" + e.toString());
    }
  }
```

At [2], if the `jobId` is random, it checks if a job with the jobId was already created successfully when all the retries failed. This can happens when an `InsertJob` fails by a timeout or intermittent network error, but actually the job has been created successfully in BigQuery backend. The retries in `BigQueryRetryHelper.runWithRetries()` may fail with `Already Exists` error, but the last check of `GetJob` returns the successfully created job properly. 

The problem is when the job is created in non-US region and no `location` is specified. For example, if the job references a dataset in `asia-northeast1`, then the job is created in `asia-northeast` and the full jobId is `<project_id>:asia-northeast1.<random_uuid>` [3].  But, `GetJob` at [2] checks `<project_id>:<random_uuid>` which searches jobs in US region (BigQuery default region). So, it cannot find the job created in `asia-northeast1` and throws `Already Exists`.

[1] https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv#java
[2] https://github.com/googleapis/java-bigquery/blob/v2.9.0/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java#L349-L416
[3] https://cloud.google.com/bigquery/docs/locations#specify_locations

**Comment by meredithslota** [comment] 2022-09-15 16:42
Reclassifying as a `bug` because we should be more resilient with `location`.

**Comment by prash-mi** [comment] 2023-02-13 08:27
Closing as I am unable to reproduce it, this looks like a one-off case which might be a result of an intermittent network issue. 
Also, in the example you mentioned that say if the job got created in `asia-northeast1` and then you get `Already Exists` as the system searches for the job in the location `US`. This is something I would expect as the backend seems to have found the job created in `asia-northeast1` in the previous retry.
Please feel free to open a new bug if this issue reoccurs.

**Closed by prash-mi** 2023-02-13 08:27 UTC
Labels: priority: p2, type: bug, api: bigquery

**Comment by baeminbo** [comment] 2023-02-14 05:24
I understand this issue happens rarely when BigQuery backend had huge latency. It's very difficult to reproduce this issue with a healthy BigQuery condition. Let me explain the issue a little bit more.

1. (client) Creates a BigQuery job without specifying location.
2. (server) BigQuery creates the job in `asia-northeast1`. The location is decided by the dataset location associated with the job. The creation is taking a long time to respond by an issue with BigQuery.  Actually, the job was successfully created in `asia-northeast1`.
3. (client) Cannot get the job creation response by timeout.
4. (client) Gets the job info just in case the job was successfully created. Some logic behind this is below:
 * If it can get the job info successfully, the client library considers it was an intermittent issue with network or timeout, so 
 handles `BigQuery.create()` as "successful". It returns the job to the caller.
 * If it cannot get the job info, the client library considers there was an issue before submitting the job inside BigQuery, so it calls job creation API again. It goes to the next steps.
 * The problem here is that the client has no way about what location was decided by BigQuery, so it tries to get the job info in `US` (default location).
5. (server) BigQuery returns no job info, because the Job UUID was queried for "US", not "asia-northeast1".
6. (client) As no job was found, the client thinks it failed before submitting the job inside BigQuery at the first attempt. 
7. (server) BigQuery returns "Already Exists" for the second attempt, because a job already exists in "asia-northeast1".
8. (client) For the "Already Exist" error for job creation, it throws an error, not retrying.

So, I believe the real problem here is the client currently has no way how location is decided by BigQuery backend. To avoid this error, I think we can run a dry-job and gets the location for getting job info the step#4 above.
